In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import os
print(os.getcwd())
print(os.listdir())

c:\hybrid_recom_project\smart_hybrid_netflix_recommender\Notebook
['content_Model.ipynb', 'EDA.ipynb', 'preprocessing.ipynb']

In [ ]:
df1 = pd.read_csv('../Data/Raw/netflix_titles.csv')
df2 = pd.read_csv(
    '../Data/Raw/mymoviedb.csv',
    engine='python',
    on_bad_lines='skip',
    encoding='latin1'
)


print("df1 columns:", df1.columns)
print("df2 columns:", df2.columns)

df1 columns: Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='str')
df2 columns: Index(['Release_Date', 'Title', 'Overview', 'Popularity', 'Vote_Count',
       'Vote_Average', 'Original_Language', 'Genre', 'Poster_Url'],
      dtype='str')

Clean + same format

In [ ]:
df1['title'] = df1['title'].str.lower().str.strip()
df2['Title'] = df2['Title'].str.lower().str.strip()

Merge

In [ ]:
df = pd.merge(df1, df2, left_on='title', right_on='Title', how='left')

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,description,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,s1,Movie,dick johnson is dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,...,"As her father nears the end of his life, filmm...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,s2,TV Show,blood & water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,"After crossing paths at a party, a Cape Town t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,s3,TV Show,ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,...,To protect his family from a powerful drug lor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,s4,TV Show,jailbirds new orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,...,"Feuds, flirtations and toilet talk go down amo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,s5,TV Show,kota factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,In a city of coaching centers known to train I...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

To understand the data,datatype,null value

In [ ]:
df.info() # use for check the column and datatype

<class 'pandas.DataFrame'>
RangeIndex: 8910 entries, 0 to 8909
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   show_id            8910 non-null   str
 1   type               8910 non-null   str
 2   title              8910 non-null   str
 3   director           6262 non-null   str
 4   cast               8083 non-null   str
 5   country            8074 non-null   str
 6   date_added         8900 non-null   str
 7   release_year       8910 non-null   int64
 8   rating             8906 non-null   str
 9   duration           8907 non-null   str
 10  listed_in          8910 non-null   str
 11  description        8910 non-null   str
 12  Release_Date       1831 non-null   str
 13  Title              1831 non-null   str
 14  Overview           1831 non-null   str
 15  Popularity         1831 non-null   float64
 16  Vote_Count         1831 non-null   str
 17  Vote_Average       1831 non-null   str
 18  Original_Language  1831 non-null   str
 19  Genre              1831 non-null   str
 20  Poster_Url         1831 non-null   str
dtypes: float64(1), int64(1), str(19)
memory usage: 1.4 MB

Convert object or string value to interger value

In [ ]:
df['listed_in'].head()

0                                        Documentaries
1      International TV Shows, TV Dramas, TV Mysteries
2    Crime TV Shows, International TV Shows, TV Act...
3                               Docuseries, Reality TV
4    International TV Shows, Romantic TV Shows, TV ...
Name: listed_in, dtype: str

Rename columns

In [ ]:
df2.rename(columns={
    'Title': 'title',
    'Genre': 'genre',
    'Overview': 'overview',
    'Popularity': 'popularity',
    'Vote_Count': 'vote_count',
    'Vote_Average': 'vote_average'
}, inplace=True)

Create TAGS column

In [ ]:
df1.fillna('', inplace=True)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,dick johnson is dead,Kirsten Johnson,,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,blood & water,,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,jailbirds new orleans,,,,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,kota factory,,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,zombie dumb,,,,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
# fill df1 (text)
df1.fillna('', inplace=True)

# convert numeric columns
num_cols = ['popularity', 'vote_count', 'vote_average']
for col in num_cols:
    df2[col] = pd.to_numeric(df2[col], errors='coerce')

# fill missing numeric values
df2[num_cols] = df2[num_cols].fillna(df2[num_cols].mean())

In [ ]:
df1['tags'] = df1['director'] + ' ' + df1['cast'] + ' ' + df1['listed_in'] + ' ' + df1['description']

In [ ]:
df2['tags'] = df2['genre'] + ' ' + df2['overview']

Convert to Lowercase

In [ ]:
df1['tags'] = df1['tags'].str.lower()
df2['tags'] = df2['tags'].str.lower()

merge both data set and remove duplicate value

In [ ]:
df = df1.merge(df2, on='title')

In [ ]:
df.drop_duplicates(subset='title', inplace=True)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,tags_x,Release_Date,overview,popularity,vote_count,vote_average,Original_Language,genre,Poster_Url,tags_y
0,s7,Movie,my little pony: a new generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",,"September 24, 2021",2021,PG,91 min,...,"robert cullen, josé luis ucha vanessa hudgens,...",2021-09-23,Equestria's divided. But a bright-eyed hero be...,137.815,190.0,8.1,en,"Animation, Family, Fantasy, Comedy, Music, Adv...",https://image.tmdb.org/t/p/original/hzq5XRGgm6...,"animation, family, fantasy, comedy, music, adv..."
1,s10,Movie,the starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,...,"theodore melfi melissa mccarthy, chris o'dowd,...",2021-09-17,A woman adjusting to life after a loss contend...,27.515,174.0,7.2,en,Drama,https://image.tmdb.org/t/p/original/gPkaPGNbjZ...,drama a woman adjusting to life after a loss c...
2,s13,Movie,je suis karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,...,"christian schwochow luna wedler, jannis niewöh...",2021-09-16,After most of her family is murdered in a terr...,19.294,20.0,5.6,de,Drama,https://image.tmdb.org/t/p/original/b25r8oFFSV...,drama after most of her family is murdered in ...
3,s14,Movie,confessions of an invisible girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",,"September 22, 2021",2021,TV-PG,91 min,...,"bruno garotti klara castanho, lucca picon, júl...",2021-09-22,When the clever but socially-awkward TetÃª joi...,62.097,144.0,7.0,pt,"Comedy, Drama",https://image.tmdb.org/t/p/original/fRxz9cKaCO...,"comedy, drama when the clever but socially-awk..."
4,s19,Movie,intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",,"September 22, 2021",2021,TV-14,94 min,...,"adam salky freida pinto, logan marshall-green,...",2021-09-22,"When a husband and wife move to a small town, ...",60.475,412.0,6.1,en,Thriller,https://image.tmdb.org/t/p/original/o6ozTBflWX...,thriller when a husband and wife move to a sma...

In [ ]:
df.describe()

       release_year   popularity    vote_count  vote_average
count   1726.000000  1726.000000   1726.000000   1726.000000
mean    2011.621089    35.039826   1774.265353      6.523928
std       10.554488    50.539837   2710.835405      0.873149
min     1946.000000    13.378000      0.000000      0.000000
25%     2008.000000    17.350750    266.250000      6.000000
50%     2016.000000    23.124000    823.000000      6.500000
75%     2018.000000    37.652750   2126.750000      7.100000
max     2021.000000  1675.161000  31077.000000      9.000000

In [ ]:
print(df.columns)

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'tags_x', 'Release_Date', 'overview', 'popularity', 'vote_count',
       'vote_average', 'Original_Language', 'genre', 'Poster_Url', 'tags_y'],
      dtype='str')

In [ ]:
df = df[['title', 'tags_x', 'genre', 'popularity', 'vote_count', 'vote_average']]

Remove duplicate titles and reset index

In [ ]:
df.drop_duplicates(subset='title', inplace=True)
df.reset_index(drop=True, inplace=True)

remove extra space (text cleaning)

In [ ]:
df['tags_x'] = df['tags_x'].str.replace(r'\s+', ' ', regex=True)

Stemming / Lemmatization
This improves recommendation quality

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    return " ".join([ps.stem(word) for word in text.split()])

df['tags_x'] = df['tags_x'].apply(stem)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1726 entries, 0 to 1725
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1726 non-null   str
 1   tags_x        1726 non-null   str
 2   genre         1726 non-null   str
 3   popularity    1726 non-null   float64
 4   vote_count    1726 non-null   float64
 5   vote_average  1726 non-null   float64
dtypes: float64(3), str(3)
memory usage: 81.0 KB

categorizing Vote_Average column

we would cut the vote_Average values and make 4 categories POPULAR,AVERAGE BELOW_AVG , NOT_POPULAR to describe it more using catigorize_col() function provided above.

In [ ]:
import numpy as np

def categorize_col(df, col, labels):

    edges = [
        df[col].min(),
        df[col].quantile(0.25),
        df[col].quantile(0.50),
        df[col].quantile(0.75),
        df[col].max()
    ]
    
    edges = np.unique(edges)  # duplicates remove + sorted
    
    df[col] = pd.cut(df[col], bins=edges, labels=labels[:len(edges)-1])
    
    return df

In [ ]:
df['vote_average'] = pd.to_numeric(df['vote_average'], errors='coerce')

In [ ]:
df['vote_average'].fillna(df['vote_average'].mean(), inplace=True)

C:\Users\thaku\AppData\Local\Temp\ipykernel_10112\1835452087.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['vote_average'].fillna(df['vote_average'].mean(), inplace=True)

0       8.1
1       7.2
2       5.6
3       7.0
4       6.1
       ...
1721    5.7
1722    6.7
1723    7.5
1724    7.3
1725    5.4
Name: vote_average, Length: 1726, dtype: float64

In [ ]:
def categorize_col(df, col, labels):

    df[col] = pd.to_numeric(df[col], errors='coerce')
    df = df.dropna(subset=[col])

    df[col] = pd.qcut(df[col], q=4, labels=labels, duplicates='drop')

    return df

In [ ]:
labels = ['not_popular', 'below_avg', 'average', 'popular']

categorize_col(df,'vote_average', labels)

df['vote_average']. unique()

array([8.1, 7.2, 5.6, 7. , 6.1, 5.8, 6.3, 6. , 7.5, 7.6, 5.9, 4. , 6.4,
       7.4, 7.8, 7.7, 6.5, 6.7, 4.6, 5.5, 6.8, 6.9, 5.1, 6.6, 5.2, 7.9,
       7.3, 5.7, 8.4, 7.1, 6.2, 8. , 8.3, 0. , 4.2, 5. , 4.9, 8.2, 5.4,
       4.7, 5.3, 8.6, 8.5, 4.1, 9. , 4.8, 4.3, 4.4, 4.5, 3.9, 3.6])

In [ ]:
df = categorize_col(df, 'vote_average', labels)

print(df['vote_average'].unique())

['popular', 'not_popular', 'average', 'below_avg']
Categories (4, str): ['not_popular' < 'below_avg' < 'average' < 'popular']

In [ ]:
df.head()

,title,tags_x,genre,popularity,vote_count,vote_average
0,my little pony: a new generation,"robert cullen, josé lui ucha vanessa hudgens, ...","Animation, Family, Fantasy, Comedy, Music, Adv...",137.815,190.0,popular
1,the starling,"theodor melfi melissa mccarthy, chri o'dowd, k...",Drama,27.515,174.0,popular
2,je suis karl,"christian schwochow luna wedler, janni niewöhn...",Drama,19.294,20.0,not_popular
3,confessions of an invisible girl,"bruno garotti klara castanho, lucca picon, júl...","Comedy, Drama",62.097,144.0,average
4,intrusion,"adam salki freida pinto, logan marshall-green,...",Thriller,60.475,412.0,below_avg

In [ ]:
#casting column into category

df ['genre'] = df['genre'].astype('category')
df['genre'].dtype

CategoricalDtype(categories=['Action', 'Action, Adventure',
                  'Action, Adventure, Animation, Family, Comedy',
                  'Action, Adventure, Animation, Science Fiction',
                  'Action, Adventure, Animation, Science Fiction, Thriller',
                  'Action, Adventure, Comedy',
                  'Action, Adventure, Comedy, Crime, Thriller',
                  'Action, Adventure, Comedy, Family',
                  'Action, Adventure, Comedy, Fantasy, Mystery',
                  'Action, Adventure, Comedy, Science Fiction',
                  ...
                  'War, Drama, Thriller', 'Western', 'Western, Action',
                  'Western, Action, Fantasy, Horror',
                  'Western, Action, Thriller, Drama', 'Western, Comedy',
                  'Western, Crime', 'Western, Drama',
                  'Western, Drama, Action, Adventure',
                  'Western, Drama, History'],
, ordered=False, categories_dtype=str)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1726 entries, 0 to 1725
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1726 non-null   str
 1   tags_x        1726 non-null   str
 2   genre         1726 non-null   category
 3   popularity    1726 non-null   float64
 4   vote_count    1726 non-null   float64
 5   vote_average  1726 non-null   category
dtypes: category(2), float64(2), str(2)
memory usage: 64.6 KB

In [ ]:
df.to_csv("../data/processed/clean_data.csv", index=False)

Missing handled
Merged datasets
Created tags
Applied stemming